author: Kevin Griffin
author_url: https://keri.one/
github_url: https://github.com/WebOfTrust/keri-swift
root_url: https://weboftrust.github.io/keri-swift/
module: keri_swift
output: docs
theme: fullwidth