name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  format:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install swiftformat
        run: brew install swiftformat
      - name: Run formatting
        run: ./scripts/format.sh .

  test:
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        xcode:
          - Xcode_13.2.app
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Show all Xcode versions
        run: ls -an /Applications/ | grep Xcode*
      - name: Change Xcode command line tools
        run: sudo xcode-select -s /Applications/${{ matrix.xcode }}/Contents/Developer
      - name: SPM Build
        run: swift build
      - name: SPM Tests
        run: swift test --parallel -Xswiftc -DDEBUG
      - name: Xcode Tests
        run: |
          swift package generate-xcodeproj
          xcodebuild -quiet -parallel-testing-enabled YES -scheme swift-extras-base64-Package -enableCodeCoverage YES build test
      - name: Codecov
        run: bash <(curl -s https://codecov.io/bash) -t ${{secrets.CODECOV_TOKEN}} -f *.coverage.txt